### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by ImagicalGamer** [ImagicalGamer/BadAdmin#1]
Commands to add
- [x] /creep <player> - Spawns creepers at a player for 10 sec
- [x] /nuke <player> - Drop a Nuke on a player

TODO:
- [x] Fix lag command make them legit lag

**Comment by Muqsit** [comment]
😆👌

**Comment by ImagicalGamer** [comment]
@Muqsit I need some help with the sendas command at line 109, I'm trying to send a message to all players posing as a player (already have that down) but I tried using implode and explode on $args[1] so they could send full sentences but I get an array to string conversion error. How to fix?
